import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { TemplateRegistry } from "better-zap";

const DEFAULT_API_VERSION = "v25.0";
const DEFAULT_CONFIG_FILES = [
  "better-zap.config.mjs",
  "better-zap.config.js",
  "better-zap.config.json",
];

type CliFlagValue = boolean | string;

type CliFlags = Record<string, CliFlagValue>;

type GenerateOptions = {
  accessToken?: string;
  apiVersion?: string;
  check?: boolean;
  fetchImpl?: typeof fetch;
  output: string;
  wabaId?: string;
};

type ResolveGenerateOptionsInput = {
  cwd: string;
  env: NodeJS.ProcessEnv;
  flags: CliFlags;
};

type GenerateConfigFile = {
  templates?: Partial<GenerateOptions>;
  whatsappTemplates?: Partial<GenerateOptions>;
  output?: string;
  accessToken?: string;
  wabaId?: string;
  apiVersion?: string;
};

type MetaTemplateButton = {
  type?: string;
  phone_number?: string;
  text?: string;
  url?: string;
};

type MetaTemplateComponent = {
  type?: string;
  format?: string;
  text?: string;
  url?: string;
  buttons?: MetaTemplateButton[];
};

type MetaTemplate = {
  name?: string;
  language?: string;
  components?: MetaTemplateComponent[];
};

type MetaTemplatesResponse = {
  data?: MetaTemplate[];
  paging?: {
    next?: string | null;
  };
  error?: {
    message?: string;
  };
};

export function parseCliArgs(argv: string[]): {
  command: string | undefined;
  flags: CliFlags;
} {
  const args = [...argv];
  const command = args.shift();
  const flags: CliFlags = {};

  while (args.length > 0) {
    const current = args.shift();
    if (!current?.startsWith("--")) {
      continue;
    }

    const flagName = current.slice(2);
    const next = args[0];
    if (!next || next.startsWith("--")) {
      flags[flagName] = true;
      continue;
    }

    const value = args.shift();
    if (value) {
      flags[flagName] = value;
    }
  }

  return { command, flags };
}

export async function resolveGenerateOptions({
  cwd,
  env,
  flags,
}: ResolveGenerateOptionsInput): Promise<GenerateOptions> {
  const configPath =
    typeof flags.config === "string"
      ? path.resolve(cwd, flags.config)
      : await findDefaultConfigPath(cwd);
  const fileConfig = configPath ? await loadConfigFile(configPath) : {};
  const templatesConfig =
    fileConfig.templates ??
    fileConfig.whatsappTemplates ??
    fileConfig;

  const outputValue =
    firstDefined(
      asString(flags.output),
      templatesConfig.output,
      env.BETTER_ZAP_TEMPLATE_OUTPUT,
    ) ?? "";
  const output = outputValue ? path.resolve(cwd, outputValue) : "";

  return {
    accessToken: firstDefined(
      asString(flags["access-token"]),
      templatesConfig.accessToken,
      env.WHATSAPP_TOKEN,
      env.META_ACCESS_TOKEN,
    ),
    wabaId: firstDefined(
      asString(flags["waba-id"]),
      templatesConfig.wabaId,
      env.WHATSAPP_BUSINESS_ACCOUNT_ID,
    ),
    apiVersion: firstDefined(
      asString(flags["api-version"]),
      templatesConfig.apiVersion,
      DEFAULT_API_VERSION,
    ),
    output,
    check: Boolean(flags.check),
  };
}

export async function fetchAllMetaTemplates({
  accessToken,
  apiVersion,
  fetchImpl = fetch,
  wabaId,
}: Required<Pick<GenerateOptions, "accessToken" | "wabaId">> &
  Pick<GenerateOptions, "apiVersion" | "fetchImpl">): Promise<MetaTemplate[]> {
  let nextUrl: string | null = `https://graph.facebook.com/${apiVersion ?? DEFAULT_API_VERSION}/${wabaId}/message_templates?limit=100`;
  const templates: MetaTemplate[] = [];

  while (nextUrl) {
    const response = await fetchImpl(nextUrl, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });

    if (!response.ok) {
      const errorPayload = (await response
        .json()
        .catch(() => ({ error: { message: `HTTP ${response.status}` } }))) as MetaTemplatesResponse;
      throw new Error(
        `[better-zap generate] Meta request failed: ${errorPayload.error?.message ?? `HTTP ${response.status}`}`,
      );
    }

    const payload = (await response.json()) as MetaTemplatesResponse;
    templates.push(...(payload.data ?? []));
    nextUrl = payload.paging?.next ?? null;
  }

  return templates;
}

export function normalizeMetaTemplates(
  metaTemplates: MetaTemplate[],
): TemplateRegistry {
  const normalizedEntries = metaTemplates
    .map((template) => [template.name, normalizeMetaTemplate(template)] as const)
    .sort(([left], [right]) => (left ?? "").localeCompare(right ?? ""));

  return Object.fromEntries(normalizedEntries);
}

export function generateTemplateRegistryFileContent(
  registry: TemplateRegistry,
): string {
  const serializedRegistry = JSON.stringify(registry, null, 2);

  return `/* eslint-disable */
// Generated by better-zap generate. Edit the source templates in Meta and re-run the generator.

import { defineTemplates } from "better-zap";

export const whatsappTemplates = defineTemplates(${serializedRegistry} as const);

export type AppWhatsAppTemplates = typeof whatsappTemplates;
`;
}

export async function writeGeneratedTemplateFile({
  check = false,
  content,
  output,
}: {
  check?: boolean;
  content: string;
  output: string;
}): Promise<void> {
  let currentContent = "";
  try {
    currentContent = await fs.readFile(output, "utf8");
  } catch (error) {
    if (!(error instanceof Error) || !(error as NodeJS.ErrnoException).code || (error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }

  if (check) {
    if (currentContent !== content) {
      throw new Error(
        `[better-zap generate] ${output} is out of date. Re-run the generator.`,
      );
    }
    return;
  }

  await fs.mkdir(path.dirname(output), { recursive: true });
  await fs.writeFile(output, content, "utf8");
}

export async function runGenerateCommand({
  accessToken,
  apiVersion = DEFAULT_API_VERSION,
  check = false,
  fetchImpl = fetch,
  output,
  wabaId,
}: GenerateOptions): Promise<{ output: string; templateCount: number }> {
  if (!accessToken || !wabaId || !output) {
    throw new Error(
      "[better-zap generate] Missing required options. Expected access token, WABA ID, and output path.",
    );
  }

  const templates = await fetchAllMetaTemplates({
    accessToken,
    apiVersion,
    fetchImpl,
    wabaId,
  });
  const registry = normalizeMetaTemplates(templates);
  const content = generateTemplateRegistryFileContent(registry);

  await writeGeneratedTemplateFile({
    check,
    content,
    output,
  });

  return {
    output,
    templateCount: Object.keys(registry).length,
  };
}

async function findDefaultConfigPath(cwd: string): Promise<string | null> {
  for (const configFile of DEFAULT_CONFIG_FILES) {
    const absolutePath = path.resolve(cwd, configFile);
    try {
      await fs.access(absolutePath);
      return absolutePath;
    } catch {
      // Try the next config filename.
    }
  }

  return null;
}

async function loadConfigFile(
  configPath: string,
): Promise<GenerateConfigFile> {
  if (configPath.endsWith(".json")) {
    const rawConfig = await fs.readFile(configPath, "utf8");
    return JSON.parse(rawConfig) as GenerateConfigFile;
  }

  const module = (await import(pathToFileURL(configPath).href)) as {
    default?: GenerateConfigFile;
  } & GenerateConfigFile;
  return module.default ?? module;
}

function normalizeMetaTemplate(template: MetaTemplate): TemplateRegistry[string] {
  if (!template.name || !template.language) {
    throw new Error("[better-zap generate] Template entry is missing name or language.");
  }

  const normalizedComponents = [];
  for (const component of template.components ?? []) {
    const type = toUpper(component.type);

    if (type === "BODY") {
      normalizedComponents.push(normalizeBodyComponent(component));
      continue;
    }

    if (type === "HEADER") {
      normalizedComponents.push(normalizeHeaderComponent(component));
      continue;
    }

    if (type === "BUTTONS") {
      normalizedComponents.push(...normalizeButtonsComponent(component));
      continue;
    }

    if (type === "FOOTER") {
      continue;
    }

    throw new Error(
      `[better-zap generate] Unsupported template component type "${component.type}" in "${template.name}".`,
    );
  }

  return {
    language: template.language,
    components: normalizedComponents,
  };
}

function normalizeBodyComponent(
  component: MetaTemplateComponent,
): NonNullable<TemplateRegistry[string]["components"]>[number] {
  return {
    type: "body",
    parameters: extractPlaceholderTokens(component.text).map((token, index) => ({
      name: createTextParameterName("body", token, index + 1),
      type: "text",
    })),
  };
}

function normalizeHeaderComponent(
  component: MetaTemplateComponent,
): NonNullable<TemplateRegistry[string]["components"]>[number] {
  const format = toUpper(component.format ?? "TEXT");

  if (format === "LOCATION") {
    return {
      type: "header",
      parameters: [{ name: "header_location", type: "location" }],
    };
  }

  if (format === "TEXT") {
    return {
      type: "header",
      parameters: extractPlaceholderTokens(component.text).map((token, index) => ({
        name: createTextParameterName("header", token, index + 1),
        type: "text",
      })),
    };
  }

  if (format === "IMAGE" || format === "VIDEO" || format === "DOCUMENT") {
    return {
      type: "header",
      parameters: [{ name: `header_${format.toLowerCase()}`, type: format.toLowerCase() as "image" | "video" | "document" }],
    };
  }

  throw new Error(
    `[better-zap generate] Unsupported header format "${component.format}".`,
  );
}

function normalizeButtonsComponent(
  component: MetaTemplateComponent,
): NonNullable<TemplateRegistry[string]["components"]> {
  return (component.buttons ?? []).map((button, index) =>
    normalizeButton(button, index),
  );
}

function normalizeButton(
  button: MetaTemplateButton,
  index: number,
): NonNullable<TemplateRegistry[string]["components"]>[number] {
  const type = toUpper(button.type);

  if (type === "QUICK_REPLY") {
    return {
      type: "button",
      subType: "quick_reply",
      index: String(index),
      parameters: [{ name: `button_${index}_payload`, type: "payload" }],
    };
  }

  if (type === "URL") {
    const tokens = extractPlaceholderTokens(button.url);
    return {
      type: "button",
      subType: "url",
      index: String(index),
      parameters: tokens.map((token, tokenIndex) => ({
        name: createTextParameterName(
          `button_${index}_text`,
          token,
          tokenIndex + 1,
        ),
        type: "text",
      })),
    };
  }

  throw new Error(
    `[better-zap generate] Unsupported button type "${button.type}" at index ${index}.`,
  );
}

function extractPlaceholderTokens(value: string | undefined): string[] {
  if (typeof value !== "string" || value.length === 0) {
    return [];
  }

  const tokens: string[] = [];
  const matcher = /\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g;
  for (const match of value.matchAll(matcher)) {
    tokens.push(match[1]);
  }
  return tokens;
}

function createTextParameterName(
  prefix: string,
  token: string | undefined,
  position: number,
): string {
  if (token && !/^\d+$/.test(token)) {
    return `${prefix}_${sanitizeName(token)}`;
  }

  return `${prefix}_${position}`;
}

function sanitizeName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9_]+/g, "_");
}

function toUpper(value: string | undefined): string {
  return typeof value === "string" ? value.toUpperCase() : "";
}

function firstDefined(...values: Array<string | undefined>): string | undefined {
  return values.find((value) => typeof value === "string" && value.length > 0);
}

function asString(value: CliFlagValue | undefined): string | undefined {
  return typeof value === "string" ? value : undefined;
}
